export const SIGN_UP_API_KEY = process.env.NEXT_PUBLIC_SIGN_UP_API_URL;
export const SIGN_IN_API_KEY = process.env.NEXT_PUBLIC_SIGN_IN_API_URL;
export const SIGN_OUT_API_KEY = process.env.NEXT_PUBLIC_SIGN_OUT_API_URL;
export const ONBOARDING_STEP_ONE_URL =
  process.env.NEXT_PUBLIC_ONBOARDING_STEP_ONE;
export const ONBOARDING_STEP_TWO_URL =
  process.env.NEXT_PUBLIC_ONBOARDING_STEP_TWO;
export const ONBOARDING_STEP_THREE_URL =
  process.env.NEXT_PUBLIC_ONBOARDING_STEP_THREE;
