import React from "react";

export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
export const POST_NEWSFEED_API_KEY = process.env.NEXT_PUBLIC_NEWSFEED_POST_URL;
export const USER_DETAILS_API_KEY = process.env.NEXT_PUBLIC_USER_DETAILS_URL;
export const SIGN_UP_API_KEY = process.env.NEXT_PUBLIC_SIGN_UP_API_URL;
export const SIGN_IN_API_KEY = process.env.NEXT_PUBLIC_SIGN_IN_API_URL;
export const SIGN_OUT_API_KEY = process.env.NEXT_PUBLIC_SIGN_OUT_API_URL;
export const ONBOARDING_STEP_ONE_URL = process.env.NEXT_PUBLIC_ONBOARDING_STEP_ONE;
export const ONBOARDING_STEP_TWO_URL = process.env.NEXT_PUBLIC_ONBOARDING_STEP_TWO;
export const ONBOARDING_STEP_THREE_URL = process.env.NEXT_PUBLIC_ONBOARDING_STEP_THREE;
export const BLOG_POST_USER_API_KEY = process.env.NEXT_PUBLIC_BLOG_POST_API;
export const BOOKMARK_NEWSFEED_API_KEY = process.env.NEXT_PUBLIC_BOOKMARK_NEWSFEED_API;
export const REACTION_NEWSFEED_API_KEY = process.env.NEXT_PUBLIC_REACTION_NEWSFEED_API;
export const COMMENT_API_KEY = process.env.NEXT_PUBLIC_COMMENTS_API;
export const NEWSFEED_COMMENT_POST_KEY = process.env.NEXT_PUBLIC_NEWSFEED_COMMENTS_POST_API;
export const SUGGESTED_USER_API = process.env.NEXT_PUBLIC_SUGGESTED_USERS;
export const FOLLOW_USER_API = process.env.NEXT_PUBLIC_FOLLOW_API;
export const FOLLOW_REQUEST_USER_API = process.env.NEXT_PUBLIC_FOLLOW_REQUEST_API;
export const CURENT_USER_LOGIN_API = process.env.NEXT_PUBLIC_USER_LOGIN_API;
export const UPDATE_PERSONAL_INFO = process.env.NEXT_PUBLIC_USER_UPDATE_PERSONAL_INFO;
export const UPDATE_CONTACT_INFO = process.env.NEXT_PUBLIC_USER_UPDATE_CONTACT_INFO;
export const USER_EDUCATION = process.env.NEXT_PUBLIC_USER_EDUCATION;
export const UPDATE_USER_WORK_EXPERIENCE = process.env.NEXT_PUBLIC_USER_UPDATE_WORK_EXPERIENCE;
export const SET_PASSWORD_API= process.env.NEXT_PUBLIC_USER_SET_PASSWORD;
export const ACCOUNT_PREFERENCE_SETTING= process.env.NEXT_PUBLIC_USER_ACCOUNT_PREFERENCE_SETTING;
export const ACCOUNT_DEACTIVATE= process.env.NEXT_PUBLIC_ACCOUNT_DEACTIVATE;
export const ADD_SKILLS= process.env.NEXT_PUBLIC_ADD_SKILLS;
export const GET_CONNECTIONS= process.env.NEXT_PUBLIC_GET_CONNECTIONS
export const GET_NOTIFICATIONS= process.env.NEXT_PUBLIC_NOTIFICATION
export const SHOW_USER_PROFILE= process.env.NEXT_PUBLIC_USER_PROFILE
export const GET_CONNECTION_AND_FOLLOWING_NEWS_FEEDS= process.env.NEXT_PUBLIC_CONNECTION_AND_FOLLOWING_NEWS_FEEDS
export const Show_USER_NEWS_FEEDS= process.env.NEXT_PUBLIC_USER_SHOW_NEWS_FEEDS
export const GET_USER_FOLLOWEES= process.env.NEXT_PUBLIC_GET_FOLLOWEES
export const GET_USER_BOOKMARKS= process.env.NEXT_PUBLIC_USER_BOOKMARKS
export const COMMENT_REPLY= process.env.NEXT_PUBLIC_COMMENT_REPLY
export const VIEW_CONNECTION= process.env.NEXT_PUBLIC_VIEW_CONNECTION
export const GROUP_API= process.env.NEXT_PUBLIC_GROUP
export const JOIN_GROUP_API= process.env.NEXT_PUBLIC_JOIN_GROUP
export const JOINED_GROUP_LISTS_API= process.env.NEXT_PUBLIC_JOINED_GROUP_LISTS
export const PAGES_API= process.env.NEXT_PUBLIC_PAGES
export const LIKE_PAGES_API= process.env.NEXT_PUBLIC_LIKED_PAGES
export const PAGE_REQUEST_API= process.env.NEXT_PUBLIC_PAGE_REQUEST
export const GROUP_MEMBERS_API= process.env.NEXT_PUBLIC_GROUP_MEMBER
export const GROUP_MEMBER_Request= process.env.NEXT_PUBLIC_GROUP_MEMBER_Request
export const HASHTAGS_API= process.env.NEXT_PUBLIC_HASHTAGS
export const BLOCK_API= process.env.NEXT_PUBLIC_BLOCK
export const SEARCH_MULTIPLE= process.env.NEXT_PUBLIC_SEARCH_MULTIPLE
export const InviteFriends= process.env.NEXT_PUBLIC_INVITE_FRIENDS
export const JOBS_API= process.env.NEXT_PUBLIC_JOBS_API
export const USE_APPLY_JOB_API= process.env.NEXT_PUBLIC_APPLY_JOBS_API
export const EVENT_API= process.env.NEXT_PUBLIC_EVENT_API
export const CATEGORY_API= process.env.NEXT_PUBLIC_CATAGEROY_API
export const PRODUCT_API= process.env.NEXT_PUBLIC_PRODUCT_API
export const MESSAGES_API= process.env.NEXT_PUBLIC_MESSAGES_API
export const CONVERSATION_API= process.env.NEXT_PUBLIC_CONVERSATION_API
export const WS_PUBLIC_API= process.env.NEXT_PUBLIC_CABLE_API
export const ADMIN_USER_API= process.env.NEXT_PUBLIC_ADMIN_USER_API
export const ADMIN_GROUP_API= process.env.NEXT_PUBLIC_ADMIN_GROUP_API
export const ADMIN_PAGE_API= process.env.NEXT_PUBLIC_ADMIN_PAGE_API
export const ADMIN_JOB_API= process.env.NEXT_PUBLIC_ADMIN_JOB_API
export const ADMIN_PRODUCT_API= process.env.NEXT_PUBLIC_ADMIN_PRODUCT_API
export const ADMIN_HASHTAG_API= process.env.NEXT_PUBLIC_ADMIN_HASHTAG_API
export const ADMIN_BLOG_API= process.env.NEXT_PUBLIC_ADMIN_BLOG_API
export const RECENT_ACTIVITY_API= process.env.NEXT_PUBLIC_ADMIN_RECENT_ACTIVITY_API
export const REPORT_API= process.env.NEXT_PUBLIC_REPORT_API
export const ADMIN_REPORT_API= process.env.NEXT_PUBLIC_ADMIN_REPORT_API
export const ADMIN_CATEGORY_API= process.env.NEXT_PUBLIC_ADMIN_CATEGORY_API
export const CONTACT_US_API= process.env.NEXT_PUBLIC_ADMIN_CONTACT_US_API

function Config() {
  return <></>;
}

export default Config;
